name: Build Package

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Pull source
        run: |
          ssh ubuntu@scooper.shithouse.tv 'cd ~/scooper-bot && git pull'
